### Business Analytics - Assignment 1 {-}


---

**Assignment Points**: 100  
**Due Date**: Friday Week 4 (17 March) @ 11.59pm  
**Submission**: Submit your file using the submission link on iLearn


- Put **all your work** into this file;
- Failure to supply solutions in the cells provided below each question will result in a loss of 30 points;
- Follow all instructions closely and **do not** print your variables to the screen unless explicitly asked to do so;
    - Comment out print statements where necessary and make sure that your submitted notebook does not have the output of previously executed print statements;
    - 10 marks will be deducted for every redundant print statement not explicitly asked for.



### About the Assignment

Credit score cards are used as a risk control method in the financial industry. Personal information submitted by credit card applicants are used to predict the probability of future defaults. The bank employs such data to decide whether to issue a credit card to the applicant or not.




| Feature Name         | Explanation     | Additional Remarks |
|--------------|-----------|-----------|
| ID | Randomly allocated client number      |         |
| Income   | Annual income  |  |
| Gender   | Applicant's Gender   | Male = 0, Female = 1  |
| Car | Car Ownership | Yes = 1, No = 0 | 
| Children | Number of Children | |
| Real Estate | Real Estate Ownership | Yes = 1, No = 0 
| Days Since Birth | No. of Days | Count backwards from current day (0), -1 means yesterday
| Days Employed | No. of Days | Count backwards from current day(0). If positive, it means the person is currently unemployed.
| Payment Default | Whether a client has overdue credit card payments | Yes = 1, No = 0



---


### Problem 1 - (50 points) {-}


**Question 1** 

- Import the `assignment_data.xlsx` file from `data` folder into a pandas DataFrame named `df`; 
- Delete duplicate rows from `df` according to `ID`;
- Delete the `ID` column.
- How many rows are left in `df`?

(10 points)

In [41]:
# add your code here
import pandas as pd

df= pd.read_excel('data/assignment_data.xlsx')
df.head(10)
#print( "original df", df)

#Deleting duplicate rows from df according to ID
df.drop_duplicates(subset="ID", keep= "first", inplace=True) 
df.drop("ID", axis=1, inplace=True)
print(len(df))


#Number of rows  left in df
num_rows = len(df)
print("Number of rows left in the dataframe:", num_rows)

5976
Number of rows left in the dataframe: 5976


--- add your text answer here


---

**Question 2**

- Reset the index in `df` using an appropriate function from `pandas` so that the new index corresponds to the number of rows (make sure to delete the old index). 
- How many positive values of `Days Employed` are there?
- Replace the positive values of `Days Employed` with 0 (zero) in `df`

(10 points)

In [43]:
# add your code here
print('original df', df)
df.head()

df=df.reset_index(drop=True)
print("Dataframe after resetting the index:", df)
df.head()

original df       Gender  Car  Real Estate  Children    Income  Days Since Birth  \
0          0    1            0         0  135000.0            -10239   
1          0    0            1         0  202500.0            -13645   
2          1    0            1         0  157500.0            -16628   
3          0    0            0         1  270000.0            -10108   
4          1    1            1         1  135000.0            -15481   
...      ...  ...          ...       ...       ...               ...   
9992       0    1            0         0  225000.0             -9479   
9993       0    1            1         2  211500.0            -10435   
9994       1    0            0         0   76500.0            -16876   
9995       0    1            1         0  180000.0            -17115   
9999       1    0            1         0  202500.0            -15047   

      Days Employed  Payment Default  
0            365243                1  
1             -5374                1  
2     

Gender  Car  Real Estate  Children    Income  Days Since Birth  \
0       0    1            0         0  135000.0            -10239   
1       0    0            1         0  202500.0            -13645   
2       1    0            1         0  157500.0            -16628   
3       0    0            0         1  270000.0            -10108   
4       1    1            1         1  135000.0            -15481   

   Days Employed  Payment Default  
0         365243                1  
1          -5374                1  
2          -3654                1  
3          -1473                1  
4          -2874                0

In [44]:
# count the number of positive values of Days Employed
positive_value = len(df[df['Days Employed'] > 0])

print('Number of positive values of Days Employed:', positive_value)

Number of positive values of Days Employed: 967


In [45]:
#Replacing positive values of Days Employed with 0 (zero) in df
df.loc[df['Days Employed'] > 0, 'Days Employed'] = 0
print(df)

      Gender  Car  Real Estate  Children    Income  Days Since Birth  \
0          0    1            0         0  135000.0            -10239   
1          0    0            1         0  202500.0            -13645   
2          1    0            1         0  157500.0            -16628   
3          0    0            0         1  270000.0            -10108   
4          1    1            1         1  135000.0            -15481   
...      ...  ...          ...       ...       ...               ...   
5971       0    1            0         0  225000.0             -9479   
5972       0    1            1         2  211500.0            -10435   
5973       1    0            0         0   76500.0            -16876   
5974       0    1            1         0  180000.0            -17115   
5975       1    0            1         0  202500.0            -15047   

      Days Employed  Payment Default  
0                 0                1  
1             -5374                1  
2             -365

--- add your text answer here

---
**Question 3**

Create two new variables in `df` named 

1. `Age`;
2. `Years in Employment`,

which measure age and employment length in **years** (decimal numbers) from `Days Since Birth` and `Days Employed` by applying approapriate transformations on these variables. 

Delete the original variables `Days Since Birth` and `Days Employed`.

(5 points)


In [46]:
# add your code here
# calculate age and years in employment
df['Age'] = round(df['Days Since Birth']/-365, 2)
df['Years in Employment'] = round(df['Days Employed']/365, 2)
print(df.head())

   Gender  Car  Real Estate  Children    Income  Days Since Birth  \
0       0    1            0         0  135000.0            -10239   
1       0    0            1         0  202500.0            -13645   
2       1    0            1         0  157500.0            -16628   
3       0    0            0         1  270000.0            -10108   
4       1    1            1         1  135000.0            -15481   

   Days Employed  Payment Default    Age  Years in Employment  
0              0                1  28.05                 0.00  
1          -5374                1  37.38               -14.72  
2          -3654                1  45.56               -10.01  
3          -1473                1  27.69                -4.04  
4          -2874                0  42.41                -7.87  


In [47]:
# drop the original variables
df = df.drop(['Days Since Birth', 'Days Employed'], axis=1)

# print the updated dataframe
print(df.head())

   Gender  Car  Real Estate  Children    Income  Payment Default    Age  \
0       0    1            0         0  135000.0                1  28.05   
1       0    0            1         0  202500.0                1  37.38   
2       1    0            1         0  157500.0                1  45.56   
3       0    0            0         1  270000.0                1  27.69   
4       1    1            1         1  135000.0                0  42.41   

   Years in Employment  
0                 0.00  
1               -14.72  
2               -10.01  
3                -4.04  
4                -7.87  


---
**Question 4**

- Create a **one**-dimensional NumPy array named `y` by exporting the first 5,000 observations of `Payment_Default`. (Hint: see `ravel()` function)
- Create a NumPy array named `X` by exporting the first 5,000 observations of the following columns `Gender`, `Car`, `Real Estate`, `Children`, `Income`, `Age`, `Years in Employment`.
 
(10 points)


In [48]:
# add your code here 
import numpy as np 
np.set_printoptions(precision=3, suppress = True)


y = np.array(df['Payment Default'].head(5000)).ravel()

x = np.array(df[['Gender', 'Car', 'Real Estate', 'Children', 'Income', 'Age', 'Years in Employment']].head(5000))
print(y)
print(x)
print(df.head())



[1 1 1 ... 0 1 0]
[[     0.        1.        0.   ... 135000.       28.05      0.  ]
 [     0.        0.        1.   ... 202500.       37.38    -14.72]
 [     1.        0.        1.   ... 157500.       45.56    -10.01]
 ...
 [     0.        1.        1.   ... 225000.       56.68      0.  ]
 [     1.        1.        1.   ...  90000.       30.58     -5.22]
 [     1.        0.        1.   ... 135000.       56.85      0.  ]]
   Gender  Car  Real Estate  Children    Income  Payment Default    Age  \
0       0    1            0         0  135000.0                1  28.05   
1       0    0            1         0  202500.0                1  37.38   
2       1    0            1         0  157500.0                1  45.56   
3       0    0            0         1  270000.0                1  27.69   
4       1    1            1         1  135000.0                0  42.41   

   Years in Employment  
0                 0.00  
1               -14.72  
2               -10.01  
3                -4.04 

---

**Question 5** 

- Use an appropriate `scikit-learn` library we learned in class to create the following NumPy arrays: `y_train`, `y_test`, `X_train` and `X_test` by splitting the data into 70% training and 30% test datasets. 
- Set `random_state` to 0 and stratify subsamples so that train and test datasets have roughly equal proportions of the target's class labels. 

(5 points) 

In [15]:
# add your code here
from sklearn.model_selection import train_test_split
x_train, x_test, Y_train, Y_test = train_test_split(x, y, test_size=0.3, random_state=0, stratify=y)
print("x_train shape: ", x_train.shape)
print("Y_train shape: ", Y_train.shape)
print("x_test shape: ", x_test.shape)
print("Y_test shape: ", Y_test.shape)

x_train shape:  (3500, 7)
Y_train shape:  (3500,)
x_test shape:  (1500, 7)
Y_test shape:  (1500,)


In [18]:
x_train

array([[ 0.000e+00,  0.000e+00,  0.000e+00, ...,  5.400e+05,  5.478e+01,
        -1.890e+00],
       [ 0.000e+00,  1.000e+00,  1.000e+00, ...,  2.250e+05,  3.497e+01,
        -6.180e+00],
       [ 0.000e+00,  1.000e+00,  1.000e+00, ...,  1.350e+05,  4.805e+01,
        -1.680e+00],
       ...,
       [ 0.000e+00,  1.000e+00,  0.000e+00, ...,  1.800e+05,  3.381e+01,
        -9.540e+00],
       [ 1.000e+00,  0.000e+00,  0.000e+00, ...,  1.350e+05,  3.265e+01,
        -4.900e+00],
       [ 0.000e+00,  1.000e+00,  1.000e+00, ...,  2.250e+05,  3.765e+01,
        -5.300e+00]])

In [19]:
x_test

array([[ 1.000e+00,  1.000e+00,  1.000e+00, ...,  4.500e+05,  2.781e+01,
        -7.620e+00],
       [ 0.000e+00,  1.000e+00,  1.000e+00, ...,  1.800e+05,  4.380e+01,
        -5.460e+00],
       [ 1.000e+00,  0.000e+00,  0.000e+00, ...,  1.350e+05,  6.645e+01,
         0.000e+00],
       ...,
       [ 0.000e+00,  0.000e+00,  1.000e+00, ...,  1.350e+05,  5.421e+01,
        -4.300e+00],
       [ 1.000e+00,  0.000e+00,  0.000e+00, ...,  2.025e+05,  4.866e+01,
        -2.336e+01],
       [ 1.000e+00,  0.000e+00,  1.000e+00, ...,  1.350e+05,  3.566e+01,
        -6.370e+00]])

---

**Question 6**

- Create new variables by using an appropriate `scikit-learn` library we learned in class to standardize the features from the training and test datasets to mean zero and variance one. Name the new variables by appending '_scaled' to the original variable names.


(10 points)   

In [27]:
# add your code here
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)
Y_train_scaled = Y_train # target variable does not need to be scaled
x_test_scaled = scaler.transform(x_test)
Y_test_scaled = Y_test # target variable does not need to be scaled

print("x_train_scaled shape: ", x_train_scaled.shape)
print("Y_train_scaled shape: ", Y_train_scaled.shape)
print("x_test_scaled shape: ", x_test_scaled.shape)
print("Y_test_scaled shape: ", Y_test_scaled.shape)


x_train_scaled shape:  (3500, 7)
Y_train_scaled shape:  (3500,)
x_test_scaled shape:  (1500, 7)
Y_test_scaled shape:  (1500,)


In [23]:
x_train_scaled

array([[-1.36878165, -0.77625003, -1.35765124, ...,  3.01314197,
         0.97073512,  0.64498503],
       [-1.36878165,  1.28824472,  0.73656619, ...,  0.28476447,
        -0.74749308, -0.01594057],
       [-1.36878165,  1.28824472,  0.73656619, ..., -0.49477196,
         0.3870059 ,  0.67733804],
       ...,
       [-1.36878165,  1.28824472, -1.35765124, ..., -0.10500375,
        -0.84810614, -0.53358859],
       [ 0.73057671, -0.77625003, -1.35765124, ..., -0.49477196,
        -0.9487192 ,  0.18125868],
       [-1.36878165,  1.28824472,  0.73656619, ...,  0.28476447,
        -0.51504222,  0.11963392]])

In [24]:
x_test_scaled

array([[ 0.73057671,  1.28824472,  0.73656619, ...,  2.23360554,
        -1.36851851, -0.23778972],
       [-1.36878165,  1.28824472,  0.73656619, ..., -0.10500375,
         0.01838047,  0.09498401],
       [ 0.73057671, -0.77625003, -1.35765124, ..., -0.49477196,
         1.98293719,  0.93616205],
       ...,
       [-1.36878165, -0.77625003,  0.73656619, ..., -0.49477196,
         0.92129594,  0.27369583],
       [ 0.73057671, -0.77625003, -1.35765124, ...,  0.08988036,
         0.43991449, -2.6627242 ],
       [ 0.73057671, -0.77625003,  0.73656619, ..., -0.49477196,
        -0.68764565, -0.04521233]])

---

## Problem 2 - (20 Points) {-}

**Question 7**

Fit the following two classifiers to the transformed training dataset using `scikit-learn` libraries.

- Perceptron - name your instance `pc` set `random_state=1`
- Logistic Regression - name your instance `lr` set `random_state=1`

When initializing instances of the above classifiers only set the parameters referenced above and nothing else.

(20 points)

In [32]:
# add your code here
from sklearn.linear_model import Perceptron,LogisticRegression

pc= Perceptron(random_state=1)
pc.fit(x_train_scaled, Y_train_scaled)
lr= LogisticRegression(random_state=1)
lr.fit(x_train_scaled, Y_train_scaled)




LogisticRegression(random_state=1)

In [30]:
print("x_train_scaled shape: ", x_train_scaled.shape)
print("Y_train_scaled shape: ", Y_train_scaled.shape)
print("x_test_scaled shape: ", x_test_scaled.shape)
print("Y_test_scaled shape: ", Y_test_scaled.shape)

x_train_scaled shape:  (3500, 7)
Y_train_scaled shape:  (3500,)
x_test_scaled shape:  (1500, 7)
Y_test_scaled shape:  (1500,)


In [31]:
x_train_scaled

array([[-1.36878165, -0.77625003, -1.35765124, ...,  3.01314197,
         0.97073512,  0.64498503],
       [-1.36878165,  1.28824472,  0.73656619, ...,  0.28476447,
        -0.74749308, -0.01594057],
       [-1.36878165,  1.28824472,  0.73656619, ..., -0.49477196,
         0.3870059 ,  0.67733804],
       ...,
       [-1.36878165,  1.28824472, -1.35765124, ..., -0.10500375,
        -0.84810614, -0.53358859],
       [ 0.73057671, -0.77625003, -1.35765124, ..., -0.49477196,
        -0.9487192 ,  0.18125868],
       [-1.36878165,  1.28824472,  0.73656619, ...,  0.28476447,
        -0.51504222,  0.11963392]])

In [33]:
pc.predict(x_train_scaled)

array([1, 1, 1, ..., 1, 1, 1])

In [34]:
pc.predict(x_test_scaled)


array([0, 1, 1, ..., 1, 1, 0])

In [35]:
lr.predict(x_train_scaled)

array([1, 1, 0, ..., 1, 1, 1])

In [36]:
lr.predict(x_test_scaled)

array([1, 0, 1, ..., 1, 1, 1])

---
## Problem 3 - (30 points) {-}


**Question 8**

- Using a method built into each of the two classifiers compute their prediction accuracies on the training data;
- Store the accuracy values into variables named according to the following pattern: `classifier_name_accuracy_train`, e.g. you should have `lr_accuracy_train`; 
- Print the two accuracy **variables** along with their brief descriptions.

(10 points)

In [37]:
# add your code here
pc_accuracy_train = pc.score(x_train_scaled, Y_train_scaled)
print("Perceptron classifier training accuracy: ", pc_accuracy_train)

lr_accuracy_train = lr.score(x_train_scaled, Y_train_scaled)
print("LogisticRegression classifier training accuracy: ", lr_accuracy_train)

Perceptron classifier training accuracy:  0.5114285714285715
LogisticRegression classifier training accuracy:  0.5577142857142857


---

**Question 9** 

- Using a method built into each of the above classifiers compute their prediction accuracy for the test dataset
- Store the accuracy values into variables named according to the following pattern: `classifier_name_accuracy_test`, e.g. you should have `lr_accuracy_test`. 
- Print the two accuracy **variables** along with brief descriptions.

(10 points)

In [49]:
# add your code here
pc_accuracy_test = pc.score(x_test_scaled, Y_test_scaled)
print("Perceptron classifier test accuracy: ", pc_accuracy_test)

lr_accuracy_test = lr.score(x_test_scaled, Y_test_scaled)
print("LogisticRegression classifier test accuracy: ", lr_accuracy_test)

Perceptron classifier test accuracy:  0.5133333333333333
LogisticRegression classifier test accuracy:  0.5073333333333333


---

**Question 10** 

Using nicely formated text in Markdown comment on the accuracies computed in Questions 8 & 9 making sure you address:
- training and test set datasets; 
- Perceptrion and Logistic Regression models. 

Are the results as expected, and why or why not? (Hint: You are not expected to comment on why a particular model is better.) 

(10 marks)


--- add your text answer here